EKS v3 Support
aws-quickstart/quickstart-cloudbees-ci pull request #31
Opened 2020-10-16 23:34 UTC by schottsfired

Highlights:
* Implement "Advanced EKS Configuration" stack
* Use framework for Spot node pool, delete Spot template
* Delete parameters that are no longer supported, add/expose new ones
* Update default CloudBees Helm chart values, e.g. separate namespace for agents by default
* Deploy all resources into `default` namespace

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-23 17:48 UTC, schottsfired commented
Thank you for https://github.com/aws-quickstart/quickstart-amazon-eks/pull/221, we pulled it in https://github.com/aws-quickstart/quickstart-cloudbees-ci/pull/31/commits/52d3273ce7ebdd61eded8b91d9bf2104c15c07b7.

Our CI is passing ✅ 
https://github.com/cloudbees/quickstart-cloudbees-ci/commits/eks-3.0

Let us know if you spot any issues with the templates @jaymccon. Looking forward to our v3 launch.

2020-10-27 19:48 UTC, jaymccon requested changes
Looking good, only small nit is that we have an updated naming scheme for entrypoint templates.

`templates/cloudbees-core-master.template.yaml` should be renamed to `templates/cloudbees-core-entrypoint-new-vpc.template.yaml` and `templates/cloudbees-core-existing-vpc.template.yaml` should be `templates/cloudbees-core-entrypoint-existing-vpc.template.yaml`.

Can also switch `cloudbees-core` to `cloudbees-ci` if you'd like. 

I will ensure that the permalinks are updated in concert with publishing the updates to s3.

2020-10-27 19:48 UTC, jaymccon commented on templates/cloudbees-core-efs.template.yaml
> -      Namespace: efs-provisioner
Is the intent that the provisiner goes into `default` namespace, I believe that is the behavior when no namespace is specified. https://github.com/aws-quickstart/quickstart-helm-resource-provider/tree/main/docs#namespace

2020-10-27 19:58 UTC, schottsfired commented on templates/cloudbees-core-efs.template.yaml
> -      Namespace: efs-provisioner
Yes, that's the intent, and it works exactly as you described.

2020-10-27 20:02 UTC, schottsfired commented
Thanks for your review @jaymccon. I'm glad you brought up the rename because I noticed it, but decided not to change (read: break) anything because of the permalinks in the deployment guide. It's great to hear that you'll take care of the permalinks, so I'll go ahead with the rename now.

2020-10-28 17:55 UTC, jaymccon approved these changes

2020-10-28 17:56 UTC, merged